In [1]:
import pandas as pd

In [3]:
ex1=pd.Series(["life",10,4.5,True])

In [4]:
print(ex1)

0    life
1      10
2     4.5
3    True
dtype: object


In [5]:
print(type(ex1))

<class 'pandas.core.series.Series'>


In [9]:
print(type(ex1[3]))

<class 'bool'>


In [10]:
ex2=pd.Series([10,20,30,40,50,60,70,80,90,100])
print(ex2)

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64


In [11]:
ex2.axes

[RangeIndex(start=0, stop=10, step=1)]

In [12]:
ex2.size

10

In [14]:
ex2.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [15]:
ex2.tail()

5     60
6     70
7     80
8     90
9    100
dtype: int64

In [16]:
ex3=pd.Series([6,8,9,1,4], index=["b","d","c","a","e"])

In [17]:
ex3


b    6
d    8
c    9
a    1
e    4
dtype: int64

In [19]:
ex3["c"]

9

In [20]:
new_ex3=ex3.sort_index()

In [21]:
new_ex3

a    1
b    6
c    9
d    8
e    4
dtype: int64

In [23]:
new2_ex3=ex3.sort_values()

In [24]:
new2_ex3

a    1
e    4
b    6
d    8
c    9
dtype: int64

In [25]:
ex3.isin([4,8])

b    False
d     True
c    False
a    False
e     True
dtype: bool

In [26]:
ex3[ex3.isin([4,8])]

d    8
e    4
dtype: int64

In [27]:
ex3.values

array([6, 8, 9, 1, 4], dtype=int64)

In [28]:
[i for i in ex3.values]

[6, 8, 9, 1, 4]

In [29]:
ex3.index

Index(['b', 'd', 'c', 'a', 'e'], dtype='object')

In [30]:
[i for i in ex3.index]


['b', 'd', 'c', 'a', 'e']

In [31]:
list(ex3.items())

[('b', 6), ('d', 8), ('c', 9), ('a', 1), ('e', 4)]

In [33]:
for index, value in ex3.items():
    print(index, "-", value)

b - 6
d - 8
c - 9
a - 1
e - 4


In [36]:
ex4=pd.Series(["+90","+49","+38","+33","+39","+46"], index=["Turkey","Germany","Ukraine","France","Italy","Sweden"])

In [37]:
ex4


Turkey     +90
Germany    +49
Ukraine    +38
France     +33
Italy      +39
Sweden     +46
dtype: object

In [38]:
ex4["Ukraine"]

'+38'

In [39]:
ex4[2]

'+38'

In [40]:
ex4["Ukraine":"Italy"]

Ukraine    +38
France     +33
Italy      +39
dtype: object

In [41]:
ex4[2:5:2]

Ukraine    +38
Italy      +39
dtype: object

In [42]:
#Creating Dataframe with List
list_ex=[6,8,2,9,20]

In [43]:
list_ex

[6, 8, 2, 9, 20]

In [49]:
pd.DataFrame(data=list_ex,columns =["VVV"], dtype="float" )

VVV
0   6.0
1   8.0
2   2.0
3   9.0
4  20.0

In [50]:
#Creating Dataframe with NumpyArray
import numpy as np

In [52]:
Ar_ex=np.random.randint(0,100,(5,5))

In [53]:
Ar_ex

array([[47, 41, 34, 41, 77],
       [42, 96,  2,  3, 13],
       [62, 31, 68,  0, 38],
       [89, 53, 10, 79, 26],
       [38, 22, 25, 14,  7]])

In [54]:
pd.DataFrame(Ar_ex, index=["a","b","c","d","e"], columns=["V1","V2","V3","V4","V5"])

V1  V2  V3  V4  V5
a  47  41  34  41  77
b  42  96   2   3  13
c  62  31  68   0  38
d  89  53  10  79  26
e  38  22  25  14   7

In [67]:
#Creating Dataframe with Dictionary
x=np.random.randint(10,50,size=8)
x

array([19, 46, 25, 17, 29, 29, 10, 26])

In [66]:
y=np.random.randint(10,50,size=8)
z=np.random.randint(10,50,size=8)
t=np.random.randint(10,50,size=8)
y

array([22, 27, 29, 28, 19, 27, 36, 38])

In [68]:
z

array([41, 18, 10, 42, 20, 30, 11, 33])

In [70]:
t

array([34, 49, 31, 34, 49, 13, 33, 41])

In [71]:
dict_ex={"val1":x,"val2":y,"val3":z,"val4":t}

In [72]:
dict_ex

{'val1': array([19, 46, 25, 17, 29, 29, 10, 26]),
 'val2': array([22, 27, 29, 28, 19, 27, 36, 38]),
 'val3': array([41, 18, 10, 42, 20, 30, 11, 33]),
 'val4': array([34, 49, 31, 34, 49, 13, 33, 41])}

In [73]:
Dt=pd.DataFrame(dict_ex)
Dt

val1  val2  val3  val4
0    19    22    41    34
1    46    27    18    49
2    25    29    10    31
3    17    28    42    34
4    29    19    20    49
5    29    27    30    13
6    10    36    11    33
7    26    38    33    41

In [75]:
#Properties of dataframes
Dt.head(2)


val1  val2  val3  val4
0    19    22    41    34
1    46    27    18    49

In [76]:
Dt.tail(1)

val1  val2  val3  val4
7    26    38    33    41

In [77]:
Dt.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [79]:
Dt.columns=["ONE","TWO","FREE","FOUR"]

In [80]:
Dt.columns

Index(['ONE', 'TWO', 'FREE', 'FOUR'], dtype='object')

In [81]:
Dt

ONE  TWO  FREE  FOUR
0   19   22    41    34
1   46   27    18    49
2   25   29    10    31
3   17   28    42    34
4   29   19    20    49
5   29   27    30    13
6   10   36    11    33
7   26   38    33    41

In [82]:
Dt.shape

(8, 4)

In [83]:
Dt.size

32